#!/bin/bash
# sign_roku.sh: Sideloads, packages, and signs the Quickbeam Roku app using a physical Roku Developer device.

# Exit immediately if any command fails
set -e

# Default values
TARGET="prod"

# Help output
show_help() {
    echo "Usage: ./sign_roku.sh -ip <ROKU_IP> -pwd <DEV_PASS> -key <SIGN_PASS> [-t <prod|beta>]"
    echo ""
    echo "Parameters:"
    echo "  -ip   : IP Address of your Roku Developer Device (e.g. 192.168.1.50)"
    echo "  -pwd  : Developer web password (set during Roku Dev mode activation)"
    echo "  -key  : Cryptographic signing password generated by running 'genkey' on Roku"
    echo "  -t    : Build target. Optional: 'prod' (default) or 'beta'"
    echo ""
    echo "Example:"
    echo "  ./sign_roku.sh -ip 192.168.1.50 -pwd mydevpassword -key mysigkeypassword -t beta"
    exit 1
}

# Parse parameters
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -ip) ROKU_IP="$2"; shift ;;
        -pwd) DEV_PASS="$2"; shift ;;
        -key) SIGN_PASS="$2"; shift ;;
        -t) TARGET="$2"; shift ;;
        -h|--help) show_help ;;
        *) echo "Unknown parameter: $1"; show_help ;;
    esac
    shift
done

# If variables are missing, prompt the user interactively
if [ -z "$ROKU_IP" ]; then
    read -p "Enter Roku TV IP Address: " ROKU_IP
fi
if [ -z "$DEV_PASS" ]; then
    read -s -p "Enter Roku Developer UI Web Password (rokudev): " DEV_PASS
    echo ""
fi
if [ -z "$SIGN_PASS" ]; then
    read -s -p "Enter Roku Cryptographic genkey Password: " SIGN_PASS
    echo ""
fi

if [ -z "$ROKU_IP" ] || [ -z "$DEV_PASS" ] || [ -z "$SIGN_PASS" ]; then
    echo "❌ Error: Roku IP, Developer Web Password, and genkey Password are required!"
    exit 1
fi

if [ "$TARGET" != "prod" ] && [ "$TARGET" != "beta" ]; then
    echo "❌ Error: Target must be 'prod' or 'beta'."
    exit 1
fi

PKG_NAME="quickbeam-${TARGET}.pkg"

echo "⚡️ Step 1: Packaging target source files into zip..."
./package_roku.sh "$TARGET"

echo "⚡️ Step 2: Sideloading app to Roku at $ROKU_IP..."
# Run sideload curl command
# Note: Roku uses digest auth for rokudev. Port 80 is used for Dev installer.
SIDELOAD_RESPONSE=$(curl -s -S -u "rokudev:$DEV_PASS" --digest -F "archive=@out/quickbeam.zip" -F "mysubmit=Install" "http://$ROKU_IP/plugin_install")

if echo "$SIDELOAD_RESPONSE" | grep -q "Install Success"; then
    echo "✅ Sideload successful!"
else
    echo "❌ Sideload failed. Please verify:"
    echo "  1. Roku developer mode is active and device is powered on."
    echo "  2. Roku IP ($ROKU_IP) is correct and reachable on your Wi-Fi."
    echo "  3. Password is correct."
    exit 1
fi

echo "⚡️ Step 3: Generating signed Roku package..."
# Post request to compile the sideloaded channel using the hardware cryptographic key
PACKAGE_RESPONSE=$(curl -s -S -u "rokudev:$DEV_PASS" --digest \
    -F "mysubmit=Package" \
    -F "passwd=$SIGN_PASS" \
    -F "app_name=quickbeam" \
    -F "pkg_time=$(date +%s)" \
    "http://$ROKU_IP/plugin_package")

# Check if package succeeded
if echo "$PACKAGE_RESPONSE" | grep -q "Failed:"; then
    echo "❌ Packaging failed! Dev ID or genkey Password might be incorrect."
    # Extract failure message if possible
    FAIL_MSG=$(echo "$PACKAGE_RESPONSE" | grep -o 'Status: Failed: [^<]*' | sed 's/Status: Failed: //' || echo "Unknown error")
    echo "Roku reports: $FAIL_MSG"
    exit 1
fi

# Locate the package download URL in the response html (it typically matches /pkgs/quickbeam.pkg)
PKG_PATH=$(echo "$PACKAGE_RESPONSE" | grep -o 'href="pkgs/quickbeam.pkg[^"]*"' | sed -e 's/href="//' -e 's/"//')

if [ -z "$PKG_PATH" ]; then
    # Fallback to default path
    PKG_PATH="pkgs/quickbeam.pkg"
fi

echo "⚡️ Step 4: Downloading signed package file from http://$ROKU_IP/$PKG_PATH..."
curl -s -S -u "rokudev:$DEV_PASS" --digest -o "out/$PKG_NAME" "http://$ROKU_IP/$PKG_PATH"

if [ -f "out/$PKG_NAME" ] && [ -s "out/$PKG_NAME" ]; then
    echo "🎉 Success! Your signed Roku package is saved to: out/$PKG_NAME"
    echo "   You can now upload this .pkg file to the Roku Stream Store (Developer Dashboard) for analysis/release."
else
    echo "❌ Download failed. The signed package was not saved."
    exit 1
fi
